In [1]:
import numpy as np

In [9]:
x =  np.arange(1, 10).reshape(3,3) #create 3*3 matrix using values from 1 to 10
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
x[2][2]

9

In [34]:
def calculate(x):
    if len(x) != 9:
        print("List must contain nine numbers")
        return
print ("mean")
print(np.mean(x, axis = 0))
print(np.mean(x, axis = 1))
print(np.mean(x))
print("\nVariance")
print(np.var(x, axis = 0))
print(np.var(x, axis = 1))
print(np.var(x))
print("\nStandard Deviation")
print(np.std(x, axis = 0))
print(np.std(x, axis = 1))
print(np.std(x))

mean
[4. 5. 6.]
[2. 5. 8.]
5.0

Variance
[6. 6. 6.]
[0.66666667 0.66666667 0.66666667]
6.666666666666667

Standard Deviation
[2.44948974 2.44948974 2.44948974]
[0.81649658 0.81649658 0.81649658]
2.581988897471611
